### ISSUE TITLE
dev-util/systemd2openrc-9999::ixit -- systemd2openrc has been renamed to systemd2rc

### ISSUE THREAD

**Issue by tsjk** [okias/ixit#6]
And thus:
install -D systemd2openrc "/tmp/portage/dev-util/systemd2openrc-9999/image//usr/bin/systemd2openrc"
/usr/bin/install: cannot stat ‘systemd2openrc’: No such file or directory
Makefile:3: recipe for target 'install' failed
make: *** [install] Error 1
 * ERROR: dev-util/systemd2openrc-9999::ixit failed (install phase):
 *   emake failed

**Comment by pavlix** [comment]
This is an obsolete report. But I realized I had to re-add systemd2rc because I accidentally removed it with Fedora tools that got their own repo. I have checked that there's no `systemd2openrc` in the whole ixit repository.
