### ISSUE TITLE
enlightenment 0.19.4 released

### ISSUE THREAD

**Issue by dirk-olmes** [okias/ixit#9]
Hi,

the E website announced a 0.19.4 release (see https://phab.enlightenment.org/phame/live/3/post/e19_4_release/)

Just copying the 0.19.2 ebuild over using the new version seems to work for me here, locally. Is this something you'd want me to provide a pull request for?

**Comment by okias** [comment]
rename, test and send pull request :)

**Comment by okias** [comment]
in tree is latest version
